In [1]:
import json
import sys
from train_json import train 
from infer_json import infer

In [2]:
file_path = './data/acall_data_simple2.json'
if file_path: #for train
    with open(file_path) as f:
        print(file_path)
        data = json.load(f)['data']

./data/acall_data_simple2.json


In [3]:
print(data)

[{'description': '6001: 내부에서 발생하는 에러입니다. Data Dictionary를 찾지 못하여 발생합니다.', 'keywords': ['6001', '6001', 'Data Dictionary', 'Data Dictionary'], 'questions': ['내부에서 발생하는 에러의 종류는?', 'Data Dictionary를 찾지 못하여 발생하는 에러의 종류는?', 'Data Dictionary를 찾지 못하여 발생하는 에러의 이름은?', '6001: 내부에서 발생하는 에러를 무엇이라고 하는가?'], 'page_num': 25}, {'description': '티베로 유틸', 'keywords': ['티베로', '티베로', '유틸리티', '유틸리티'], 'questions': ['유틸 티베베로 유틸 틸티베베베 베베베리 유틸 티베드로 유틸이 유틸하게 틸팅 유틸구 유틸사 티허  유틸 티', '티베로 유틸리티', '티베로로 유틸리티 티베로 틸티베로 유틸이 티베로를 티베롤로 티베 로 유틸을 티가 무엇 틸틸리티?   유틸리티  티베', '티베로로 유틸리티 티베로 틸티베로 유틸이 티베로를 티베롤로 티베 로 유틸을 티가 무엇 틸틸리티?   유틸리티리티 유틸'], 'page_num': 79}, {'description': '티베로 유틸리티', 'keywords': ['티베로 유틸리티', '티베로 유틸리티', '티베로', '티베로'], 'questions': ['티베베로 유틸리티의 제목은 티베로유틸리티가 무엇과 함께 무엇에 대한 유틸리 티베   티베어 티베 로 유틸 어 티베드로 유틸즈 티베', '티베베로 유틸리티의 이름은?', '티베베베로 유틸리티를 무엇으로 하면?', '티베베베로 유틸리티를 무엇으로 하는가 티베로유틸리티?'], 'page_num': 80}, {'description': '유틸리티', 'keywords': ['티베로 유틸리티', '티베로 유틸리티'], 'questions': ['유틸리티를 무엇이라고 할까??', '유틸리티를 무엇이라고 할까

In [4]:
label_list = []
for item in data:
    label_list.append('페이지: '+str(item['page_num']))
print(label_list)

['페이지: 25', '페이지: 79', '페이지: 80', '페이지: 81']


In [11]:
import torch
from torch.nn import Softmax

x = torch.tensor([[-0.6011904,   1.6675575,  -0.37542316, -0.51154095, -0.13037324],
 [-0.5540767,   1.3629862,  -0.2956285,  -0.4676193,  -0.0876275]])

In [12]:
print(x)

tensor([[-0.6012,  1.6676, -0.3754, -0.5115, -0.1304],
        [-0.5541,  1.3630, -0.2956, -0.4676, -0.0876]])


In [14]:
m = torch.nn.Softmax(dim=1)
print(m(x))

tensor([[0.0684, 0.6614, 0.0857, 0.0748, 0.1096],
        [0.0849, 0.5773, 0.1099, 0.0926, 0.1353]])


In [24]:
m = torch.nn.Softmax(dim=1)
#input = torch.randn(2, 3)
input = torch.tensor([[-2., 4.],])
output = m(input)
print(input)
print(output)

tensor([[-2.,  4.]])
tensor([[0.0025, 0.9975]])
